# -*- coding: utf-8 -*-
"""Cópia de Exercício 1 - Análise Exploratória.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkL_YgiFJB7j1seNWaAIUMwjzcrHZqy8
"""

# Import pandas e o matplotlib


# Importe o dataset autos para um Pandas Dataframe

# 1. Exibir as 10 primeiras linhas da base

import pandas as pd

df = pd.read_csv("autos.csv")

print(df.head(10))

# 2. Verificar o tipo de dados de cada coluna

import pandas as pd

df = pd.read_csv("autos.csv")

print(df.dtypes)

# 3. Quantas linhas e colunas há na base?

import pandas as pd

df = pd.read_csv("autos.csv")

linhas, colunas = df.shape
print(f"Número de linhas: {linhas}")
print(f"Número de colunas: {colunas}")

# 5. Mostrar estatísticas descritivas somente para colunas numéricas

import pandas as pd

df = pd.read_csv("autos.csv")

print(df.describe())

# 6. Listar os diferentes tipos de carroceria (`body_style`). Não é somente listar a coluna body_style

import pandas as pd

df = pd.read_csv("autos.csv")

tipos_carroceria = df['body-style'].unique()
print("Tipos de carroceria disponíveis:")
print(tipos_carroceria)

# 7. Contar quantos carros existem de cada fabricante (`make`)

import pandas as pd

df = pd.read_csv("autos.csv")

contagem_fabricantes = df['make'].value_counts()
print("Quantidade de carros por fabricante:")
print(contagem_fabricantes)

# 8. Calcular a média do preço (`price`)

import pandas as pd

df = pd.read_csv("autos.csv")

media_preco = df['price'].mean()
print(f"Média de preço dos carros: {media_preco:.2f}")

# 9. Mostrar a média de preço por tipo de carroceria

import pandas as pd

df = pd.read_csv("autos.csv")

media_por_carroceria = df.groupby('body-style')['price'].mean()
print("Média de preço por tipo de carroceria:")
print(media_por_carroceria)

# 10. Exibir o carro mais caro da base

import pandas as pd

df = pd.read_csv("autos.csv")

carro_mais_caro = df.loc[df['price'].idxmax()]
print("Carro mais caro da base:")
print(carro_mais_caro)

# 11. Exibir todos os carros com mais de 5 cilindros

import pandas as pd

df = pd.read_csv("autos.csv")

carros_mais_de_5_cilindros = df[df['num-of-cylinders'] > 5]

print("Carros com mais de 5 cilindros:")
print(carros_mais_de_5_cilindros)

# 12. Quantos carros são conversíveis?

import pandas as pd

df = pd.read_csv("autos.csv")

quantidade_conversiveis = df[df['body-style'] == 'convertible'].shape[0]
print(f"Quantidade de carros conversíveis: {quantidade_conversiveis}")

# 13. Qual é a média de consumo (city_mpg) dos carros com motor `medium`?

import pandas as pd

df = pd.read_csv("autos.csv")

media_consumo_medium = df[df['engine_size'] == 'medium']['city-mpg'].mean()
print(f"Média de consumo (city-mpg) dos carros com motor 'medium': {media_consumo_medium:.2f}")

# 14. Exibir todos os carros com preço acima da média geral

import pandas as pd

df = pd.read_csv("autos.csv")

media_preco = df['price'].mean()

carros_acima_da_media = df[df['price'] > media_preco]

print("Carros com preço acima da média geral:")
print(carros_acima_da_media)

# 15. Fazer um gráfico de barras com a quantidade de carros por tipo de carroceria

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("autos.csv")

contagem_carroceria = df['body-style'].value_counts()

plt.figure(figsize=(8, 5))
contagem_carroceria.plot(kind='bar', color='skyblue', edgecolor='black')

plt.title('Quantidade de Carros por Tipo de Carroceria')
plt.xlabel('Tipo de Carroceria')
plt.ylabel('Quantidade')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()